#!/usr/bin/env ruby

require 'drb'
pwd = File.dirname(__FILE__)
require "#{pwd}/../environment"

if ARGV[0] == '--help'
   print "Usage: script/drb_client <bind_ip> <port>"
   exit
end

bind_ip = ARGV[0] || 'localhost'
port = ARGV[1] || 5750

$controller = DRbObject.new(nil, "druby://#{bind_ip}:#{port}")