#!/usr/bin/env ruby

pwd = File.dirname(__FILE__)
require_relative "#{pwd}/../environment"

Dir["#{pwd}/../app/startup/*.rb"].each do |file|
  puts "Starting up $file"
  load "#{file}"
end

while 1
   sleep 1000
end
